<?php

return [
    'Bagong Buhay E Elementary School',
    'Bagong Buhay G Elementary School',
    'Bagong Buhay I Elementary School (Lawang Pare)',
    'Benito Nieto Elementary School',
    "City of San Jose del Monte Indigenous People's Education School",
    'Daniel A. Avena Elementary School',
    'Francisco Homes Elementary School',
    'Gaya-Gaya Elementary School',
    'Goldenville Elementary School',
    'Graceville Elementary School',
    'Guijo Elementary School',
    'Gumaok Elementary School',
    'Heroesville Elementary School',
    'Kakawate Elementary School',
    'Kaypian Elementary School',
    'Marangal Elementary School',
    'Marangal Elementary School Annex',
    'Minuyan Elementary School',
    'Mulawin Elementary School',
    'Muzon (Pabahay 2000) Elementary School',
    'Paradise Farms Community School',
    'Partida Elementary School',
    'Ricafort Elementary School',
    'San Isidro Elementary School',
    'San Jose del Monte Central School',
    'San Jose del Monte Heights Elementary School',
    'San Manuel Elementary School',
    'San Martin (BBC) Elementary School',
    'San Rafael (BBH) Elementary School',
    'San Roque Elementary School',
    'Sapang Palay Proper Elementary School',
    'Sta. Cruz (BBD) Elementary School',
    'Sto. Cristo Elementary School',
    'Towerville Elementary School',
    'Tungkong Mangga Elementary School',
    'Citrus National High School',
    'City of San Jose del Monte National Science High School',
    'Graceville National High School',
    'Kakawate National High School',
    'Kaypian National High School',
    'Marangal National High School',
    'Eduardo A. Abendaño National High School',
    'Mulawin National High School',
    'Muzon Harmony Hills High School',
    'Angelito M. Sarmiento High School',
    'Paradise Farms National High School',
    'San Isidro National High School',
    'San Jose del Monte Heights High School',
    'San Jose del Monte National High School',
    'San Jose del Monte National Trade School',
    'San Manuel National High School',
    'San Martin National High School',
    'San Rafael National High School',
    'Sapang Palay National High School',
    'Sto. Cristo National High School',
    'Towerville High School',
    'Bagong Buhay A Integrated School',
    'Bagong Buhay B Integrated School',
    'Bagong Buhay F Integrated School',
];
